return {
  ["timestamp"] = 1640768082,
  ["data"] = {
    ["my_idx"] = 2,
    ["power"] = 0,
    ["len"] = 2,
    ["rank_list"] = {
      [1] = {
        ["idx"] = 1,
        ["leader_face_update_time"] = 0,
        ["power"] = 10592,
        ["leader_avatar_bid"] = 1000,
        ["leader_lev"] = 200,
        ["leader_rid"] = 3,
        ["leader_look_id"] = 120402,
        ["leader_face"] = 20402,
        ["leader_srvid"] = "dev_2",
        ["leader_face_file"] = "",
        ["members_max"] = 15,
        ["leader_name"] = "超神de伊迪丝",
        ["lev"] = 1,
        ["name"] = "233",
        ["members_num"] = 1,
      },
      [2] = {
        ["idx"] = 2,
        ["leader_face_update_time"] = 0,
        ["power"] = 0,
        ["leader_avatar_bid"] = 1000,
        ["leader_lev"] = 35,
        ["leader_rid"] = 1,
        ["leader_look_id"] = 110401,
        ["leader_face"] = 10401,
        ["leader_srvid"] = "dev_2",
        ["leader_face_file"] = "",
        ["members_max"] = 15,
        ["leader_name"] = "风de璐易丝",
        ["lev"] = 1,
        ["name"] = "111",
        ["members_num"] = 1,
      },
    },
    ["num"] = 100,
    ["gname"] = "111",
    ["leader_name"] = "风de璐易丝",
    ["time"] = 1640768082,
    ["start"] = 1,
    ["glev"] = 1,
  },
}